### ISSUE TITLE
Add documentation for plugins

### ISSUE THREAD

**Issue by haarp** [linuxmint/xed#122]
I've been trying to port some Pluma/gedit Python plugins to xed, but I'm not having much success. gedit plugins tend to import some gedit gi modules that don't exist, while Pluma plugins seem to use python2 instead, which xed won't work with.

Could some documentation be created to explain how to write/port plugins?

Many thanks!

**Comment by rwmills** [comment]
I second this. Also needed is documentation and an example on how to use the plugin template, generate-plugin.py and preprocessor.py.

I use HTML Tidy a lot and would be willing to create a plugin to run it in xed.

The lack of HTML Tidy is enough to fore me to install Gedit and use it instead of xed.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Xed. Your suggestion was reviewed. I'll try to look into this at some point but can't promise it will happen soon. In many cases you mostly just need to rename some of the gedit names to xed to get you close.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
