### ISSUE TITLE
key repeated at file chooser dialog

### ISSUE THREAD

**Issue by yuzhichang** [linuxmint/xed#134]
Tried opening a file, at the file chooser dialog I typed a key to filter filenames begin with that character, then the character was repeated at the search box. See the attached picture.
That is annoying. Is it possible to disable the search box?

xed version: 1.2.2+serena
Mint version: 18.1

![screenshot_2017-06-03_15-30-57](https://cloud.githubusercontent.com/assets/153784/26751723/febac320-4872-11e7-8356-d7a1c7b97cf8.png)

**Comment by JosephMcc** [comment]
I can't reproduce this. The behavior of this is a bit strange. To even get the search bar to show you need to first click something in the sidebar and then use Ctrl+F. Hitting esc will then switch you back to the normal pathbar.

In any case this is not a xed issue. The dialog is provided by Gtk and the problem is with GtkFileChooserDialog.

**Comment by yuzhichang** [comment]
This issue is gone after I switch input method from ibus to scim.
Terminator + ibus has a similar problem, see https://bugs.launchpad.net/terminator/+bug/1318542.
