### ISSUE TITLE
Gedit Plugins For XED

### ISSUE THREAD

**Issue by bananabob** [linuxmint/xed#16]
With gedit you can install plugins.

I currently have the following installed from the gedit.org :
Bookmarks
Bracket Completion
Change Case
Document Statistics
File Browser Pane
Insert Date/Time
Modelines
Sort
Spell Checker
Tag List

I have also installed gEdit project manager from https://sourceforge.net/projects/gedit-fileset/

And there is one plugin that is only available for gEdit V3 which I would use if I could - gedit-favorites
https://github.com/Quixotix/gedit-favorites

Could these be made available in XED please.

**Comment by unkilbeeg** [comment]
Comprehensive Regular Expressions.  I've heard there is a plugin for gEdit, but I've never used it.  I've been using nedit for years because although it's ugly as sin, it has incredibly good regular expression support.  I haven't found a graphical text editor that compares.  I'll use Pluma or GEdit for most things (better support for specialized characters, etc.) but if I have any complex searches to do I'll save it and restart it in nedit.  It would be really, really nice to find a modern graphical editor with regular expressions.  SciTE has regular expressions, but they were a little limited last time I tried to use them.

**Comment by Winterwolf** [comment]
I second that question! I need simple ability to switch tabs by ctrl+tab and [here is](https://github.com/Flynsarmy/GEdit3TabSwitch) a good plugin for this, but I don't know, what to do with it.

**Comment by mcarans** [comment]
I would like the Advanced Find Replace plugin or something like it (which ties in with @unkilbeeg request above)

**Comment by KevinNadaud** [comment]
Concerning the code comment plugin, it is possible to add an option to change the associated shortcut ? Or maybe a plugin to change all the shortcut ?

**Comment by JosephMcc** [comment]
This was closed automatically by a merged commit. Just wanted to follow up a bit.

I don't know that we can directly support the use of Gedit plugins but what we did do was port our internals and our plugin system to a nearly identical system. This should make porting of many gedit plugins fairly easy. As a quick test of the new system I was able to port the Terminal python3 plugin from gedit-plugins to xed in about 10 minutes. It's mostly a case of name changes.
