### ISSUE TITLE
Initiative from gedit developers to make the code more re-usable

### ISSUE THREAD

**Issue by swilmet** [linuxmint/xed#17]
Not an issue, just an information. I'm a gedit and GtkSourceView developer.

You should be aware of these initiatives:
https://wiki.gnome.org/Apps/Gedit/ReusableCode
https://wiki.gnome.org/Projects/GtkSourceView/MdiFramework

And I've started this project recently:
https://github.com/swilmet/gtef

For what is worth, I don't like the new gedit UI with the headerbar, I prefer a traditional menubar and toolbar. But the gedit core (without the plugins) still contains ~40k lines of code. Ideally most of that code should be shared with a library, and the application would just need to glue things up together.

**Comment by clefebvre** [comment]
Hi Sebastien,

Many thanks for this and many thanks for your work on gedit and GtkSourceView.

A common lib would allow us to implement different frontends / UI while working together on the same core, thus allowing us to reuse the work done in GNOME, but without completely forking it. I won't go through the many benefits, as they're quite obvious for both sides.

(This isn't really a new fork (it's basically the DE-agnostic continuation of the Pluma fork) but the idea is the same).

I remember talking with Jasper about this. GNOME is obviously heading somewhere we don't want to go and many applications, after being patched more and more heavily, are now getting forked. Some of them are designed as implementation of their own core libs though, and that highlights some of the other reasons why forks are sometimes necessary.

If you look at the history of the Cinnamon project for instance, before it was given snapping, resizable tiling and all, the reason mutter was forked wasn't to create a different WM, but simply to keep the API stable. We couldn't work with Mutter, not because of what it was, but because of how it was developed. It changed drastically every 6 months, and its only scope was the new upcoming GNOME Shell. For Cinnamon to be shipped to various distributions, each running different versions of Mutter, it was a challenge to adapt to its lack of backward compatibility and to its many refactorings.

If I look at gtef here for instance, which definitely sounds like something we should consider migrating to, in theory at least, what immediately strikes me is that it depends on GTK 3.20. It's not a big deal and it's probably quite easy to make it compatible with previous GTK versions (we're committed all the way to 3.14 in terms of development targets), but it's very important for us, if we're going to use something and rely on it going forward, that the commitment is there on what matters to us. It cannot change, or break, or lose compatibility with our targets.. if it did, because we'd have to support both new and old versions we'd start having more and more ifdefs in the code, and juggling with hacks, until eventually it would become simpler to drop the dependency. It means discipline and commitment would be required upstream. All desktop environments would need to be supported and included in the scope, redesigns/refactoring wouldn't be allowed to break existing apps etc etc.. 

It's a case by case story and nobody has the right to demand that level of commitment or to misinterpret  the scope of a particular GNOME project. It is important though, if we work together on shared code, that that code does what we need it to and for the long run and that its scope is defined and includes all the project relying on it.

I wouldn't say it's easy to come up with something like gtef, and I really appreciate the effort. That's the technical side though, the code as a shareable resource. It's good but it's not enough. The scope and goal of the project have to be defined, the framework needs to reach maturity (I assume it's already quite stable... but by maturity I mean its design has to be stable, to guarantee upcoming changes/refactors will be as small as possible and won't impact applications using it), backward compatibility is key.

The code matters. As you say it was 40k lines of code over there in Pluma which weren't in gedit all these years. It's not even really duplicating efforts... efforts are being made on both sides and don't benefit everybody. So it's a pity. Here with Xed, we essentially have "yet another fork", it's not really the same story repeating itself... and although the code is indeed forked and duplicated, we're actually focusing effort here with this rather than spreading it.

What really matters to me, much more than the code, are the ideas and the people involved. I'm sure gtef could work for instance, but what's interesting isn't gtef itself, its code and the code removal it would mean in Xed/Pluma/gedit. What's much more interesting is you, me, the MATE team, the GNOME team working together. Before we talk about design and code and framework, we need to talk about goals, commitment, and have everybody understand what matters to everybody else. After that we can hopefully find common grounds and benefit from each other's work.

**Comment by swilmet** [comment]
The Gtef library is far from finished though, it's just the early beginnings.

For the dependency on GTK+ 3.20, it's how most GNOME software is developed. With each new version of GTK+, there is usually a few things to adapt, e.g. not using deprecated APIs. If that maintenance work is done regularly, every 6 months, when GTK+ 4 will be released it'll be much easier to port the code, since the first steps are already done. And I prefer to not clutter my code with ifdefs that checks various versions of GTK+.

Anyway, I hope that Gtef will become one day feature-full enough to develop easily a new text editor. And I hope that gedit will be ported to Gtef (it's complicated because of the plugins API, ideally the plugins should not break). And if the remaining code in the gedit core is quite small, then it'll be much easier to create (and maintain in the long term) a fork that has a traditional UI. And if one day that happens, you'll be able to use an older version that has old enough dependencies (but I guess that systems like [Flatpak](https://blogs.gnome.org/mclasen/2016/06/07/modularity-and-the-desktop/) will be the preferred way to develop and use an application).

**Comment by clefebvre** [comment]
Thanks Sebastien,

Good luck, I look forward to seeing how this develops.

PS: I was delighted to see https://blogs.gnome.org/desrt/2016/06/13/gtk-4-0-is-not-gtk-4/ today. It addresses a lot of the concerns I mentioned above.
