### ISSUE TITLE
compile xed for mac

### ISSUE THREAD

**Issue by phantomxe** [linuxmint/xed#234]
**Issue** 
I like xed and i'm using on lm18 without a problem. But i want to compile xed on mac (MacOS El Capitan). 
```
checking for gmodule-2.0... yes
checking for
	libxml-2.0 >= 2.5.0
	glib-2.0 >= 2.40.0
	gmodule-2.0
	gthread-2.0 >= 2.13.0
	gio-2.0 >= 2.40.0
	gtk+-3.0 >= 3.19.3
	gtksourceview-3.0 >= 3.19.0
	libpeas-1.0 >= 1.12.0
	libpeas-gtk-1.0 >= 1.12.0
    xapp
... no
configure: error: Package requirements (
	libxml-2.0 >= 2.5.0
	glib-2.0 >= 2.40.0
	gmodule-2.0
	gthread-2.0 >= 2.13.0
	gio-2.0 >= 2.40.0
	gtk+-3.0 >= 3.19.3
	gtksourceview-3.0 >= 3.19.0
	libpeas-1.0 >= 1.12.0
	libpeas-gtk-1.0 >= 1.12.0
    xapp
) were not met:

No package 'xapp' found
```
I got this error message. Is it possible compile to mac? or dream?

**Comment by mtwebster** [comment]
I *really* doubt it, not without heavy patching - xapp relies greatly upon the x11 dependency.  Looking at xed's source, it looks like it only uses the XAppPreferencesWindow class out of that library.  You might be able to alter the build for yourself by removing the other class files from the build, as well as the x11 dependencies.  As a bonus, It uses the meson build system, so it's reasonably easy to modify the build.

We've never targeted anything but Linux/x11 systems, otherwise we'd have build conditionals for this stuff.

**Comment by phantomxe** [comment]
I cleaned all files includes "xed-preferences-dialog". But
```
make[3]: *** No rule to make target `xed-preferences-dialog.c', needed by `xed-preferences-dialog.lo'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
How can i remove that properly? 😄

**Comment by mtwebster** [comment]
I was saying to modify the xapps package.  I can't do anything this second, I'll see if I can make a branch later that might compile

**Comment by mtwebster** [comment]
You can try building this branch of xapps: https://github.com/mtwebster/xapps/tree/no-x
```
meson builddir --prefix=/usr
ninja -C builddir
ninja -C builddir install
```
Adjust to suit.. if this doesn't work I'm not sure there's anything more, this just isn't something we target.

**Comment by JosephMcc** [comment]
I'm going to close this since it isn't something we actually support. Doesn't stop you from discussing it. I'm not sure how much luck you're going to have with this even if you did manage to get it building. Looking at gedit which does support building/running on the mac, there is a lot of Mac specific stuff going on.
