### ISSUE TITLE
hiding scrollbars

### ISSUE THREAD

**Issue by Bert-de-Jong** [linuxmint/xed#244]
Using 1.8.3 on Mint 19.
When the mouse cursor is not on scrollbars, the scrollbars decrease in size and become partially transparent.
Evolution is doing the same thing.
How to stop this behavior?

**Comment by Bert-de-Jong** [comment]
Hi Joseph.

I've looked into the issue, and I hereby request you reopen this ticket as a feature request.
I'll explain why below.

_In the past..._
GTK+ had Ubuntu overlay scrollbars. There were various ways to disable them, including `export LIBOVERLAY_SCROLLBAR=0`, apt removing various (lib)overlay-scrollbar* packages, via programs (gsettings, gconf-editor, gnome-tweaks, etc) and via various GUIs provided by window managers.

_Noaways..._
The toolkit itself no longer offers an overlay scrollbar setting, to prevent such a blanket toolkit toggle from breaking applications that haven't been tested with both combinations. The overlay nature of the scrollbars is now part of the toolkit. To allow application developers to decide what their applications should look like, the toolkit provides a mechanism to opt-out or add a setting for users.

The function [gtk_scrolled_window_set_overlay_scrolling()](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#gtk-scrolled-window-set-overlay-scrolling) can be used to enable/disable overlay scrolling. Application developers can optionally use [GSettings](https://blog.gtk.org/2017/05/01/first-steps-with-gsettings/) to have a user setting bound to the property.

**Comment by leigh123linux** [comment]
@Bert-de-Jong 

Why expect some lame ubuntu commands to stop GTK overlay-scrollbar?
If you want to disable it use 

```
export GTK_OVERLAY_SCROLLING=0
```
see the arch wiki for more info

https://wiki.archlinux.org/index.php/GTK+#Disable_overlay_scrollbars

**Comment by Bert-de-Jong** [comment]
That's excellent, leigh123linux.
Thanks; problem solved.

**Comment by Bert-de-Jong** [comment]
Still request to open this as a feature request.

They've dropped GTK_OVERLAY_SCROLLING in master:
https://github.com/GNOME/gtk/commit/e49615184a9d85bb0bb4e289b3ee8252adee3813#diff-3cf94c6e1eb009e20985034bc2210bfd

**Comment by Bert-de-Jong** [comment]
Still request to open this as a feature request.

They've [dropped](https://github.com/GNOME/gtk/commit/e49615184a9d85bb0bb4e289b3ee8252adee3813#diff-3cf94c6e1eb009e20985034bc2210bfd) GTK_OVERLAY_SCROLLING in master.

**Comment by leigh123linux** [comment]
@Bert-de-Jong  Dropping GTK_OVERLAY_SCROLLING in master (gtk4) isn't an issue as we're likely to be gtk3 based for many years.

**Comment by Bert-de-Jong** [comment]
And users who don't like the overlay scrollbars will eventually learn about GTK_OVERLAY_SCROLLING.

GTK_OVERLAY_SCROLLING will probably become common knowledge soon, given that more and more users are moving to LTS releases Ubuntu Bionic (26 April 2018) and Mint Tara (29 June 2018).

**Comment by mtwebster** [comment]
The cinnamon setting mentioned uses that environment variable, I'm not sure what the feature request is about?

See:
https://github.com/linuxmint/cinnamon-session/blob/master/cinnamon-session/main.c#L342

This has been here since cinnamon 3.0.  Depending on our setting, the environment variable is set session-wide (which is why the settings UI says you need to log out for it to take effect.)

There's really nothing we can do about the eventuality of gtk4 and the inability to disable them there.  This sort of trend is a large part of the reason we have our own apps we try to maintain now - xed, xplayer, etc...  If someone decides to use a gtk4 app down the road, this will simply be one of the issues they need to factor into their decision to use it.
