### ISSUE TITLE
How to add Xed menus from a python plugin ?

### ISSUE THREAD

**Issue by stuaxo** [linuxmint/xed#305]
```
 * Xed version (xed --version)
xed --version                                                                                                     INT(-2) ↵  stu@computer  2566  02:26:15 
xed - Version 2.0.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 18.10
```
I'm working on a python plugin that I've got working in Gedit and Pluma.   I'm trying to work out how to make menus work in Xed.

Are they more like Gedit or Pluma.

Ideally I'd be able to use Gio.Menu(), but having trouble working out how I can add a menu with items.

Is there are existing python plugin I can look at ?

**Comment by collinss** [comment]
Hi @stuaxo, currently xed doesn't use Gio for the menus. It's still using an older (and deprecated) method for creating them. However, I'm currently working on cleaning up all this deprecated stuff, and porting everything to Gio for menus and actions and Gtk.Builder rather than Gtk.UIManager. If all goes well and I can get the porting done with my currently busy schedule, then Gio.Menu will be the way to do it for future versions of Xed. If you want to target the current version, you will need to do it using Gtk.UIManager and Gtk.Actions.

**Comment by stuaxo** [comment]
OK, I'm a little rusty, but I guess on window there is a method like get_ui_manager()

I'm trying to build a shim library to make it easier to build plugins, as part of that I'll let the user pass me a gio menu and parse it to make an old style xml menu.

**Comment by collinss** [comment]
It may help to look at the textsize plugin in this repository. It's in python and also adds some menu items.

**Comment by stuaxo** [comment]
Cheers, I've been looking at that (but always forget it's that one that is the python plugin when I come back).

When it comes to the differences, the menus and panel are quite a big difference.

Then there are small things, where methods have the same names, but slightly different signatures - e.g. gedit has a column_pos on create_tab_from_location which is missing on Xed.

Will close this is as not an issue as such.
