### ISSUE TITLE
CTRL Navigation to new line start issue

### ISSUE THREAD

**Issue by jmholla** [linuxmint/xed#322]
```
 * Xed version - 2.0.2
 * Distribution - Mint 19.1
```

**Issue**
When a line starts with spaces or tabs, CTRL left from the beginning of the first word goes to the end of the previous line instead of the beginbning of the whitespace.

**Steps to reproduce**
Write a python function in xed. Try to CTRL+left navigate from any line that doesn't start in the first column.

**Expected behaviour**
It should go to the beginning of the current line, before all the white space.

**Other information**
I don't know if there is a standard for this, but I have never had this behavior with any other editor.

**Comment by collinss** [comment]
It is indeed weird behavior, though I get the same with gedit. As near as I can tell, this is an issue with GtkSourceView, which is upstream from us (and also explains why gedit does it too). You'll have to file a bug report with them. In the mean time, I'm going to close this because there's nothing we can do about it.
