### ISSUE TITLE
Selected Text Should Not Change Font Size With Zooming Shortcuts

### ISSUE THREAD

**Issue by anonyco** [linuxmint/xed#327]
```
 * Xed version (xed --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

When I select a stretch of text, I can press Ctrl + +, Ctrl + -, and Ctrl + 0 to change the font size. This should not be the case or at least there should be a setting to disable this behavior if this behavior is intentional.

**Steps to reproduce**

1. Select any stretch of text.
2. While the text is selected, press Ctrl + + or Ctrl + -

**Expected behaviour**

The selected text changes font size.

**Comment by icarter09** [comment]
@anonyco
 1) Can you provide the Xed and Distro versions?
 2) What should the case be for pressing `Ctrl + + ` or ` Ctrl + -`?
 3) Is this a feature request? The only difference between VSC and Sublime Text compared to Xed on this functionality is that Xed changes font size on the selected text while the other two will do it to the entire file when `Ctrl + +` or `Ctrl + -` is pressed. That's why I don't see this as a bug.

**Comment by anonyco** [comment]
The problem is that this program displays a plain text file, so it's a superfluous, awkward, and unusable feature to allow changing the font size of specific portions of text. In my mind, this feature is much more likely to cause problems than do good.

**Comment by collinss** [comment]
My first thought was that maybe it's for printing purposes, since xed has the ability to print text files, but it seems that the text sizes you set are ignored in that case. But yeah, this is probably overkill. I think it would generally be better for the text to all scale together, regardless of selection - unless there were some way of preserving the larger text, which doesn't seem to be the case. On the other hand, this may not be handled on our end (I haven't checked in the source code yet, but a lot of that kind of stuff is actually inherited from GtkSourceView which we don't control), so that might pose some challenges to changing the behavior.

**Comment by anonyco** [comment]
I would assume that if it is handled by GTK, then GTK might have some way to disable this function to reduce overhead for performance reasons.
