### ISSUE TITLE
Contrast of the blue text on a dark background makes it hard to read

### ISSUE THREAD

**Issue by caelwithcats** [linuxmint/xed#364]
```
 * Xed version (2.2.7)
 * Distribution - (Mint 19.1)
```

**Issue**

The blue text on the dark background when Mint-Y-Dark is turned on is hard to read with code.

![](https://i.postimg.cc/zf4S2jVk/Screenshot-from-2020-03-31-10-06-57.png)
You can only see the blue text faintly.

**Comment by JosephMcc** [comment]
Yeah. There isn't a lot we can do about this. The classic source view theme is really meant to be used with a dark theme. You pretty much just need to set a new theme if you want to use a dark gtk theme.

**Comment by LinuxOnTheDesktop** [comment]
Let me add to this bug report a reference to a similar problem (or rather set of problems). That other problem appears as [this](https://github.com/linuxmint/mint20.2-beta/issues/53) issue on the Mint 20.2 beta tracker. I mention that issue here because otherwise when that beta page gets retired that report is liable to get almost completely lost.
