### ISSUE TITLE
Tiling windows with certain themes not possible

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/xed#73]
I'm using Linux Mint 18.1 (64-bit) Cinnamon 3.2.7

I noticed the following:

1. Set `Controls` in the theme chooser to one of the `Mint-Y` themes or to `Adwaita`.
2. Open `xed` and try to tile the xed window. It's possible to tile it top/bottom, but it's not possible to tile left/right or to tile in 1/4.
3. After opening the search bar, tiling is possible. After closing the search bar, tiling is still possible.

This doesn't happen with `Controls` set to `Mint-X`or `High-Contrast`.

Can anybody confirm this? Or should I provide more information? If yes, which ones?

**Comment by JosephMcc** [comment]
What is the screen resolution? Are you using English or another translation?

**Comment by NikoKrause** [comment]
German translation. Screen resolution 1280x800 (best my machine can do). I tried it with other screen resolutions as well. Same result. Do I need to compile xed by myself?

**Comment by NikoKrause** [comment]
Okay. I compiled the git master xed 1.2.2

With German translation I can't tile and the above mentioned workaround with opening the searchbar doesn't work anymore. It happens now also with `Mint-X`.

In the English translation it's now the situation like I described above. Can tile only after opening the searchbar.

**Comment by JosephMcc** [comment]
It's changed because there is now an extra button in the searchbar. It is weird that opening the searchbar then allows you tile. Ultimately whether or not you can tile is decided by the minimum width that the window wants in a certain direction. This can be affected by translations because they can change the length of strings and thus change that minimum requirement. Themes can also affect it because one may use different padding values in the widgets compared to another. In the end this isn't really a bug but just how it works. The only thing that seems strange is that opening the search bar changes it. It must change the size request of something in the window that then allows you to tile. I would imagine if you had a bit larger screen res you wouldn't see this at all. I don't on 1920x1080.

**Comment by NikoKrause** [comment]
Hmmm... A little bit unsatisfying. It never happened in the past. And it doesn't happen with other editors. Is there nothing, what can be done about it? Increasing the min width or something?

**Comment by JosephMcc** [comment]
Well increasing the minimum width would just make it worse if you think about. It's possible it could be improved. It's a matter of tracking down the particular object that limiting the size and see if it can be tweaked a bit.

Do you remember if it happened before the addition of the new searchbar? In older Xed versions.

**Comment by NikoKrause** [comment]
It happened somewhere in the process of upgrading to Linux Mint 18.1.
In Linux Mint 18 I hadn't this issue.
I can check older versions of xed. Before the searchbar was added. And after it was added.
I'll inform you after my research.

**Comment by JosephMcc** [comment]
I think you answered my question. I don't think we had the search in 18. It was new in 18.1. That at least gives a starting point where the problem might lie.

**Comment by NikoKrause** [comment]
I now compiled a few versions of xed.

The tiling was fine with the tag of xed 1.2.1: 2133a2f5b5ad6d5dce3269ecabdd5e509044937e
The issue begins after the "x" close button was added to the searchbar: aa31c09fc7c4a38bd79e049a5dd9c0d8f23d8add

**Comment by Laurencio** [comment]
I find myself with same problem with xed no tiling left/right nor corners on LM 18.3 XFCE. Xed 1.6.3
Didn't have this issue on LM 18.1

**Comment by franckgaga** [comment]
Same problem here with LM 18.3 Cinnamon 3.6.7 in french with 1366x768 resolution display.

**Comment by SethosII** [comment]
I also have this problem in a fresh installation of Linux Mint 19 with Cinnamon 3.8.7 and xed 1.8.2. My screen resolution is 1366x768.
