### ISSUE TITLE
(xed:21418): GLib-GIO-ERROR **: Settings schema 'org.x.editor' does not contain a key named 'toolbar-buttons-style'

### ISSUE THREAD

**Issue by ali1234** [linuxmint/xed#88]
Not sure if this is the right place to report, but with embrosyn's PPA on Ubuntu 16.04 I get the following:

    (xed:21418): GLib-GIO-ERROR **: Settings schema 'org.x.editor' does not contain a key named 'toolbar-buttons-style'
    Trace/breakpoint trap (core dumped)

**Comment by JosephMcc** [comment]
Not sure what the problem is. We ship 1.2.2 in Mint which is what is in the PPA. Can you double check the version you have? I grabbed the source from the ppa just to double check and it seems to be proper for 1.2.2. A quick search showed no references to that key. You probably need to contact the PPA maintainer.

**Comment by ali1234** [comment]
I had an old version in /usr/local.
